@ADDR_LINE1 = 12455 Jim Dhamer Dr
@ADDR_LINE2 = 
@ADDR_CITY = 
@ADDR_STATE = IL
@ADDR_POSTAL = 
@ADDR_COUNTRY = US

POST {{GOOGLE_BASE}}/v1:validateAddress?key={{GOOGLE_API_KEY}}
Content-Type: application/json

{
  "address": {
    "regionCode": "{{ADDR_COUNTRY}}",
    "addressLines": ["{{ADDR_LINE1}}","{{ADDR_CITY}}"]
  }
}


